filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Eugene, Welcome to Coot version 0.8.9.1")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Eugene. Welcome to Coot 0.8.9.1")
set_display_lists_for_maps (0)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
handle_read_draw_molecule_with_recentre ("/dls/labxchem/data/2021/lb22717-23/processing/analysis/panddas/processed_datasets/CD44MMA-x0448/CD44MMA-x0448-pandda-input.pdb", 1)
handle_read_draw_molecule_with_recentre ("/dls/labxchem/data/2021/lb22717-23/processing/analysis/model_building/CD44MMA-x0448/CD44MMA-x0448-pandda-model.pdb", 1)
use_graphics_interface_state ()
