(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Eugene, Welcome to Coot version 0.8.9.1")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Eugene. Welcome to Coot 0.8.9.1")
(set-display-lists-for-maps 0)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "/dls/labxchem/data/2021/lb22717-23/processing/analysis/panddas/processed_datasets/CD44MMA-x0448/CD44MMA-x0448-pandda-input.pdb" 1)
(handle-read-draw-molecule-with-recentre "/dls/labxchem/data/2021/lb22717-23/processing/analysis/model_building/CD44MMA-x0448/CD44MMA-x0448-pandda-model.pdb" 1)
(use-graphics-interface-state)
