#!/bin/bash
#PBS -q default
#PBS -P PanddaScore
#PBS -j oe
#PBS -N Job_Name_1
#PBS -l walltime=24:00:00

np=$(cat ${PBS_NODEFILE} | wc -l);

conda activate pandda_env
cd /dls/labxchem/data/2018/lb18145-80/processing/analysis/eugene/pandda_score
python training/analysis/model_analysis.py -m /dls/labxchem/data/2018/lb18145-80/processing/analysis/eugene/pandda_score/training_results/2022_09_20-07_29_42_PM/model_2022_09_20-07_29_42_PM_saved.pth -d training_data_paths/training_set.csv